services:
  bigtech.api:
    image: ${DOCKER_REGISTRY-}bigtechapi
    build:
      context: .
      dockerfile: BigTech.Api/Dockerfile

  bigtechdb:
    image: postgres

  rabbitmq:
    image: rabbitmq:3-management

  distributedcache:
    image: redis

  prometheus:
    image: prom/prometheus
    
  grafana:
    image: grafana/grafana

networks:
  mynw: