services:
  bigtech.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__PostgresSQL=Server=bigtechdb;Port=5432;Database=Bigtech;User Id=admin;Password=admin;Include Error Detail=true
      - RabbitMq__HostName=rabbitmq
      - RabbitMq__Port=5672
      - Redis__Url=distributedcache
    ports:
      - "7070:8080"
      - "7071:8081"
    depends_on:
      - bigtechdb
      - rabbitmq
      - distributedcache
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  bigtechdb:
    container_name: bigtechdb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=Bigtech
    restart: always
    volumes:
      - /var/lib/postgresql/data/
    ports:
        - "5432:5432"

  rabbitmq:
    container_name: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    volumes:
      - /var/lib/rabbitmq
    ports:
        - "1010:15672"
        - "5670:5672" 

  distributedcache:
    container_name: distributedcache
    restart: always
    ports:
      - "6379:6379"
  
  prometheus:
    container_name: "prometheus"
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - mynw
    
  grafana:
    container_name: "grafana"
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - mynw